name: GARCE

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cmake=3.17
  - cudatoolkit-dev=10.1
  - cudnn=7.6
  - cupti=10.1
  - cxx-compiler=1.1
  - gxx_linux-64=7.3
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.7
  - cupy=8.2.0
  - nodejs=14
#  - nvcc_linux-64=10.1
  - pip=20.1
  - python=3.7
